"""empty message

Revision ID: 1e7876bb02ac
Revises: 488ed23f4cdb
Create Date: 2020-06-12 02:33:31.356756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e7876bb02ac'
down_revision = '488ed23f4cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('google_creds_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('last_gdrive_sync', sa.DateTime(), nullable=True),
    sa.Column('evernote_token', sa.String(), nullable=True),
    sa.Column('test_field', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_test_field'), 'user', ['test_field'], unique=True)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_index('ix_users_test_field', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('id', name='tags_id_key')
    )
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('google_creds_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_gdrive_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('evernote_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('test_field', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.UniqueConstraint('id', name='users_id_key')
    )
    op.create_index('ix_users_test_field', 'users', ['test_field'], unique=True)
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_user_test_field'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
