"""empty message

Revision ID: 410764ffe43e
Revises: 3f1fe36deab4
Create Date: 2020-05-29 13:54:21.171135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410764ffe43e'
down_revision = '3f1fe36deab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.String(), nullable=False))
    op.drop_constraint('users_id__key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'id_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_id__key', 'users', ['id_'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
