"""empty message

Revision ID: 488ed23f4cdb
Revises: dac5e215af6c
Create Date: 2020-06-12 02:30:06.066264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488ed23f4cdb'
down_revision = 'dac5e215af6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test_field', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_test_field'), 'users', ['test_field'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_test_field'), table_name='users')
    op.drop_column('users', 'test_field')
    # ### end Alembic commands ###
