"""empty message

Revision ID: b65f13b0ab29
Revises: d96e2808bd19
Create Date: 2020-06-07 14:39:36.382769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65f13b0ab29'
down_revision = 'd96e2808bd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_gdrive_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_gdrive_sync')
    # ### end Alembic commands ###
