"""empty message

Revision ID: bff77a32749c
Revises: 1e7876bb02ac
Create Date: 2020-06-12 02:35:34.685792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff77a32749c'
down_revision = '1e7876bb02ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'tag', ['tag_id'])
    op.drop_column('tag', 'id')
    op.add_column('user', sa.Column('user_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_id'])
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.add_column('tag', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'tag_id')
    # ### end Alembic commands ###
