"""empty message

Revision ID: d96e2808bd19
Revises: 410764ffe43e
Create Date: 2020-06-05 13:16:11.193579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd96e2808bd19'
down_revision = '410764ffe43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_creds_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_creds_json')
    # ### end Alembic commands ###
